const mongoose = require('mongoose');

const teaSchema = new mongoose.Schema(
    {
        name: { type: String, required: true },
        description: { type: String, required: true },
        price: { type: Number, required: true },
        image: { type: String, required: true },
        ingredients: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Ingredient' }],
        benefits: [{ type: String }],
        caffeineLevel: { type: String, enum: ['None', 'Low', 'Medium', 'High'] },
        stock: { type: Number, required: true, default: 0 },
        rating: { type: Number, required: true, default: 0 },
        numReviews: { type: Number, required: true, default: 0 },
        isAIMixture: { type: Boolean, default: false }, // if generated by AI
        mixGoal: { type: String }, // optional, for AI generated teas
        isPublished: { type: Boolean, default: true },
        source: { type: String, enum: ['catalog', 'ai'], default: 'catalog' },
        createdFromSuggestion: { type: mongoose.Schema.Types.ObjectId, ref: 'AISuggestion' },
    },
    { timestamps: true }
);

const Tea = mongoose.model('Tea', teaSchema);
module.exports = Tea;
